#root -l -b -q  'Display_SignalFits_LL_QCD.cc("outputs/datacards/","","HH_mX_HH_LL_QCD_",750, 1,false,false)'
#root -l -b -q  'Display_SignalFits_LL_QCD.cc("outputs/datacards/","","HH_mX_HH_LL_QCD_",750, 1,true,false)'
#root -l -b -q  'Display_SignalFits_LL_QCD.cc("outputs/datacards/","","HH_mX_HH_LL_QCD_",800, 1,false,false)'
#root -l -b -q  'Display_SignalFits_LL_QCD.cc("outputs/datacards/","","HH_mX_HH_LL_QCD_",800, 1,true,false)'
#root -l -b -q  'Display_SignalFits_LL_QCD.cc("outputs/datacards/","","HH_mX_HH_LL_QCD_",1000, 1,false,false)'
#root -l -b -q  'Display_SignalFits_LL_QCD.cc("outputs/datacards/","","HH_mX_HH_LL_QCD_",1000, 1,true,false)'
root -l -b -q  'Display_SignalFits_LL_QCD.cc("outputs/datacards/","","HH_mX_HH_LL_QCD_",1200, 1,false,false)'
root -l -b -q  'Display_SignalFits_LL_QCD.cc("outputs/datacards/","","HH_mX_HH_LL_QCD_",1200, 1,true,false)'
root -l -b -q  'Display_SignalFits_LL_QCD.cc("outputs/datacards/","","HH_mX_HH_LL_QCD_",1400, 1,false,false)' 
root -l -b -q  'Display_SignalFits_LL_QCD.cc("outputs/datacards/","","HH_mX_HH_LL_QCD_",1400, 1,true,false)'
root -l -b -q  'Display_SignalFits_LL_QCD.cc("outputs/datacards/","","HH_mX_HH_LL_QCD_",1600, 1,false,false)'
root -l -b -q  'Display_SignalFits_LL_QCD.cc("outputs/datacards/","","HH_mX_HH_LL_QCD_",1600, 1,true,false)'
root -l -b -q  'Display_SignalFits_LL_QCD.cc("outputs/datacards/","","HH_mX_HH_LL_QCD_",1800, 1,false,false)'
root -l -b -q  'Display_SignalFits_LL_QCD.cc("outputs/datacards/","","HH_mX_HH_LL_QCD_",1800, 1,true,false)'
root -l -b -q  'Display_SignalFits_LL_QCD.cc("outputs/datacards/","","HH_mX_HH_LL_QCD_",2000, 1,false,false)'
root -l -b -q  'Display_SignalFits_LL_QCD.cc("outputs/datacards/","","HH_mX_HH_LL_QCD_",2000, 1,true,false)'
root -l -b -q  'Display_SignalFits_LL_QCD.cc("outputs/datacards/","","HH_mX_HH_LL_QCD_",2500, 1,false,false)'
root -l -b -q  'Display_SignalFits_LL_QCD.cc("outputs/datacards/","","HH_mX_HH_LL_QCD_",2500, 1,true,false)'
root -l -b -q  'Display_SignalFits_LL_QCD.cc("outputs/datacards/","","HH_mX_HH_LL_QCD_",3000, 1,false,false)'
root -l -b -q  'Display_SignalFits_LL_QCD.cc("outputs/datacards/","","HH_mX_HH_LL_QCD_",3000, 1,true,false)'
#root -l -b -q  'Display_SignalFits_LL_QCD.cc("outputs/datacards/","","HH_mX_HH_LL_QCD_",4000, 1,false,false)'
#root -l -b -q  'Display_SignalFits_LL_QCD.cc("outputs/datacards/","","HH_mX_HH_LL_QCD_",4000, 1,true,false)'
#root -l -b -q  'Display_SignalFits_LL_QCD.cc("outputs/datacards/","","HH_mX_HH_LL_QCD_",4500, 1,false,false)'
#root -l -b -q  'Display_SignalFits_LL_QCD.cc("outputs/datacards/","","HH_mX_HH_LL_QCD_",4500, 1,true,false)'


