#root -l -b -q  'Display_SignalFits_TT.cc("outputs/datacards/","","HH_mX_HH_TT_",750, 1,false,false)'
#root -l -b -q  'Display_SignalFits_TT.cc("outputs/datacards/","","HH_mX_HH_TT_",750, 1,true,false)'
#root -l -b -q  'Display_SignalFits_TT.cc("outputs/datacards/","","HH_mX_HH_TT_",800, 1,false,false)'
#root -l -b -q  'Display_SignalFits_TT.cc("outputs/datacards/","","HH_mX_HH_TT_",800, 1,true,false)'
#root -l -b -q  'Display_SignalFits_TT.cc("outputs/datacards/","","HH_mX_HH_TT_",1000, 1,false,false)'
#root -l -b -q  'Display_SignalFits_TT.cc("outputs/datacards/","","HH_mX_HH_TT_",1000, 1,true,false)'
root -l -b -q  'Display_SignalFits_TT.cc("outputs/datacards/","","HH_mX_HH_TT_",1200, 1,false,false)'
root -l -b -q  'Display_SignalFits_TT.cc("outputs/datacards/","","HH_mX_HH_TT_",1200, 1,true,false)'
root -l -b -q  'Display_SignalFits_TT.cc("outputs/datacards/","","HH_mX_HH_TT_",1400, 1,false,false)' 
root -l -b -q  'Display_SignalFits_TT.cc("outputs/datacards/","","HH_mX_HH_TT_",1400, 1,true,false)'
root -l -b -q  'Display_SignalFits_TT.cc("outputs/datacards/","","HH_mX_HH_TT_",1600, 1,false,false)'
root -l -b -q  'Display_SignalFits_TT.cc("outputs/datacards/","","HH_mX_HH_TT_",1600, 1,true,false)'
root -l -b -q  'Display_SignalFits_TT.cc("outputs/datacards/","","HH_mX_HH_TT_",1800, 1,false,false)'
root -l -b -q  'Display_SignalFits_TT.cc("outputs/datacards/","","HH_mX_HH_TT_",1800, 1,true,false)'
root -l -b -q  'Display_SignalFits_TT.cc("outputs/datacards/","","HH_mX_HH_TT_",2000, 1,false,false)'
root -l -b -q  'Display_SignalFits_TT.cc("outputs/datacards/","","HH_mX_HH_TT_",2000, 1,true,false)'
root -l -b -q  'Display_SignalFits_TT.cc("outputs/datacards/","","HH_mX_HH_TT_",2500, 1,false,false)'
root -l -b -q  'Display_SignalFits_TT.cc("outputs/datacards/","","HH_mX_HH_TT_",2500, 1,true,false)'
root -l -b -q  'Display_SignalFits_TT.cc("outputs/datacards/","","HH_mX_HH_TT_",3000, 1,false,false)'
root -l -b -q  'Display_SignalFits_TT.cc("outputs/datacards/","","HH_mX_HH_TT_",3000, 1,true,false)'
#root -l -b -q  'Display_SignalFits_TT.cc("outputs/datacards/","","HH_mX_HH_TT_",4000, 1,false,false)'
#root -l -b -q  'Display_SignalFits_TT.cc("outputs/datacards/","","HH_mX_HH_TT_",4000, 1,true,false)'
#root -l -b -q  'Display_SignalFits_TT.cc("outputs/datacards/","","HH_mX_HH_TT_",4500, 1,false,false)'
#root -l -b -q  'Display_SignalFits_TT.cc("outputs/datacards/","","HH_mX_HH_TT_",4500, 1,true,false)'


